FROM oracle/glassfish:5.0-web
MAINTAINER Jan Weinschenker <jan.weinschenker@holisticon.de>
COPY ./target/Servlet4PrimeFaces.war /glassfish5/glassfish/domains/domain1/autodeploy
EXPOSE 8080:8080
EXPOSE 8181:8181
EXPOSE 4848:4848
