FROM oracle/glassfish:5.0-web
MAINTAINER Jan Weinschenker <jan.weinschenker@holisticon.de>
COPY ./target/Servlet4Push.war /glassfish5/glassfish/domains/domain1/autodeploy
EXPOSE 8080:8082
EXPOSE 8181:8182
EXPOSE 4848:8842
